// <auto-generated />
using System;
using Boticario.Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Boticario.Infraestructure.Migrations
{
    [DbContext(typeof(BoticarioContext))]
    [Migration("20200708020343_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Boticario.Domain.Entities.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Codigo");

                    b.Property<DateTime>("Data");

                    b.Property<int>("Revendedor_Id");

                    b.Property<int>("Status");

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("Revendedor_Id");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("Boticario.Domain.Entities.Revendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("NomeCompleto")
                        .IsRequired();

                    b.Property<string>("Senha")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Revendedores");
                });

            modelBuilder.Entity("Boticario.Domain.Entities.Test1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Test1");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Diego"
                        });
                });

            modelBuilder.Entity("Boticario.Domain.Entities.Compra", b =>
                {
                    b.HasOne("Boticario.Domain.Entities.Revendedor", "Revendedor")
                        .WithMany("Compras")
                        .HasForeignKey("Revendedor_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
